# Rustfmt configuration for the Tauri project
# See https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
tab_spaces = 4
use_small_heuristics = "Default"
newline_style = "Unix"

# Import formatting
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Function/struct formatting
fn_args_layout = "Tall"
struct_lit_single_line = true
where_single_line = false

# Comments
wrap_comments = false
comment_width = 100
normalize_comments = false

# Chains and match arms
chain_width = 60
match_block_trailing_comma = true
match_arm_leading_pipes = "Never"

# Misc
use_field_init_shorthand = true
use_try_shorthand = true
force_multiline_blocks = false
format_strings = false
